# Generated by Django 3.1.3 on 2020-11-11 08:17

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201108_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='static/default_avatar.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
    ]
