# Generated by Django 3.1.3 on 2020-11-22 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_auto_20201123_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUserLikes',
            new_name='PostUserLike',
        ),
    ]
